TAG_ARCHITECTURE = 'architecture'
TAG_BUILT = 'built'
TAG_DISTRIBUTION = 'distribution'
TAG_EXCLUDED = 'excluded'
TAG_INCLUDED = 'included'
TAG_NAME = 'name'
TAG_PACKAGES = 'packages'
TAG_SPECIE = 'specie'
